# Generated by Django 5.0 on 2024-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(default=0, upload_to='photo/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='trianing',
            field=models.BooleanField(default=False),
        ),
    ]
