# Generated by Django 5.0 on 2024-01-02 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employees_image_employees_trianing'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
