# Generated by Django 5.0 on 2024-01-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employees_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('achivment', models.CharField(max_length=50)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
        ),
    ]
